### ISSUE TITLE
 help I can't get it to work

### ISSUE THREAD

**Issue by Carloscb22** [nickj609/GameModeManager#1]
Hello, I have tried everything to make it work but I can't.
I have the modded Counter-Strike 2 (CS2) Modded but when I install this plugin it loads but the css_modes or css_maps commands do not work and I don't know what I'm doing wrong.

In this way I have edited the gamemodes_server.txt

[gamemodes_server.txt](https://github.com/nickj609/GameModeManager/files/14793436/gamemodes_server.txt)

And this gives me the sv logs:
2024-03-28 04:56:01.880 -03:00 [INFO] plugin:GameModeManager OnMapGroupCommand execution started
2024-03-28 04:56:01.881 -03:00 [INFO] plugin:GameModeManager Map group command detected!
2024-03-28 04:56:01.882 -03:00 [INFO] plugin:GameModeManager Current MapGroup is .
2024-03-28 04:56:01.882 -03:00 [INFO] plugin:GameModeManager New MapGroup is .
2024-03-28 04:56:01.882 -03:00 [INFO] plugin:GameModeManager Mapgroup is the same. Not updating map list...

I hope you can help me...

**Comment by nickj609** [comment]
Hey @Carloscb22, thanks for bringing this to my attention. I have one other report of this behavior. I will be doing some thorough testing tomorrow afternoon (EST) and will report back here with an update. It is likely that a new version will be released to address this issue so I will keep you posted.

**Comment by Carloscb22** [comment]
Thank you so much! We remain attentive to your reports!

**Comment by nickj609** [comment]
@Carloscb22, do you by chance still have the Ultimate Map Chooser plugin installed? If so, would you be able to remove it to see if the issue persists?

**Comment by nickj609** [comment]
Hey @Carloscb22, can you try the new version and see if you are still experiencing issues? If so, can you provide me with the output of the logs?

**Comment by Carloscb22** [comment]
Hello!! Sorry for the delay, I just installed the update and tried to run it but I get these errors from the console:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: No current scenario
   at ExecutesPlugin.Managers.GameManager.GetCurrentScenario() in /home/runner/work/cs2-executes/cs2-executes/Managers/GameManager.cs:line 163
   at ExecutesPlugin.ExecutesPlugin.OnRoundStart(EventRoundStart event, GameEventInfo info) in /home/runner/work/cs2-executes/cs2-executes/ExecutesPlugin.cs:line 568
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invo
1 1 1
ke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
[Executes] Trying to loop valid active players.
[Executes] [Psicosis] Adding timer for allocation...
Server tick 16886 expected to be long because 'RestartRound'
['Psicosis' tick 16887 depth=4 (6459..6462) ping=23ms loss in/out = 11.71%/11.71%] CQ catchup: removed 4, max: 10, 10 ticks this frame
[S_API FAIL] Tried to access Steam interface SteamUtils010 before SteamAPI_Init succeeded.
[Executes] Player is first T, allocating bomb.
L 04/01/2024 - 05:48:07: "Psicosis<0><[U:1:75668651]><TERRORIST>" triggered "Got_The_Bomb"
[Executes] Allocating...
GetUserSetting: cvar 'cl_interp_ratio' unknown.
GetUserSetting: cvar 'cq_netgraph' unknown.
['Psicosis' tick 17163 depth=2 (6756..6757) ping=22ms loss in/out = 10.62%/10.62%] CQ bloat: removed 10, max: 10, 10 ticks this frame
['Psicosis' tick 17199 empty starved 16=250.0ms ping=22ms loss in/out = 10.62%/10.62%] generating substitute command 6805 from 6804
L 04/01/2024 - 05:48:12: World triggered "Round_Start"
[Executes] EventHandler::OnRoundFreezeEnd
05:48:12 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: No current scenario
   at ExecutesPlugin.Managers.GameManager.GetCurrentScenario() in /home/runner/work/cs2-executes/cs2-executes/Managers/GameManager.cs:line 163
   at ExecutesPlugin.ExecutesPlugin.OnRoundFreezeEnd(EventRoundFreezeEnd event, GameEventInfo info) in /home/runner/work/cs2-executes/cs2-executes/ExecutesPlugin.cs:line 436
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
['Psicosis' tick 19919 depth=2 (9548..9549) ping=23ms] CQ bloat: removed 12, max: 10, 10 ticks this frame
```

**Comment by Carloscb22** [comment]
logs:

```
2024-04-01 05:51:11.390 -03:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/tcagame_svc5048/carlosb/5048/game/csgo/addons/counterstrikesharp/plugins/GameModeManager/GameModeManager.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Cannot find MapGroup 'File': /home/steam/cs2/game/csgo/gamemodes_server.txt
   at GameModeManager.Plugin.OnConfigParsed(Config config) in C:\Users\nickj\OneDrive\Documents\CS2\plugins\GameModeManager\Config.cs:line 26
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 339
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 217
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

```

this is my gameserver.txt:
[gamemodes_server.txt](https://github.com/nickj609/GameModeManager/files/14821780/gamemodes_server.txt)

**Comment by Carloscb22** [comment]
Once inside the server it also doesn't let me use the !maps (css_maps) or !modes (css_modes) commands.

**Comment by nickj609** [comment]
@Carloscb22, can you delete the old version of the configuration file and then reload the plugin or restart the server? The file you need to delete is /game/csgo/addons/counterstrikesharp/configs/plugins/GameModeManager/GameModeManager.json.

**Comment by Carloscb22** [comment]
I have deleted the previous version of the configuration and when loading it, this appears in the console:

```
L 04/01/2024 - 12:40:50: "Psicosis<0><[U:1:75668651]><CT>" say "!css_maps"
12:40:50 [INFO] (plugin:GameModeManager) OnMapsCommand execution started.
SteamNetworkingSockets lock held for 5.6ms.  (Performance warning.)  ServiceThread,RecvUDPPacket
This is usually a symptom of a general performance problem such as thread starvation.
12:40:55 [INFO] (plugin:GameModeManager) OnMapsCommand execution started.
12:41:03 [INFO] (plugin:GameModeManager) OnMapsCommand execution started.
['Psicosis' tick 5980 depth=2 (1886..1887) ping=22ms] CQ bloat: removed 13, max: 10, 10 ticks this frame
['Psicosis' tick 5988 depth=2 (1914..1915) ping=22ms] CQ bloat: removed 17, max: 10, 10 ticks this frame
['Psicosis' tick 5995 depth=2 (1941..1942) ping=23ms] CQ bloat: removed 18, max: 10, 10 ticks this frame
['Psicosis' tick 6003 depth=2 (1966..1967) ping=24ms] CQ bloat: removed 15, max: 10, 10 ticks this frame
['Psicosis' tick 6257 depth=2 (2243..2244) ping=23ms loss in/out = 3.05%/3.05%] CQ bloat: removed 10, max: 10, 10 ticks this frame
['Psicosis' tick 6283 empty starved 16=250.0ms ping=22ms loss in/out = 3.05%/3.05%] generating substitute command 2276 from 2275
['Psicosis' tick 6299 empty starved 32=500.0ms ping=23ms loss in/out = 3.05%/3.05%] generating substitute command 2292 from 2291
12:41:22 [INFO] (plugin:GameModeManager) OnModesCommand execution started.
12:41:30 [INFO] (plugin:GameModeManager) OnModesCommand execution started.
```

The problem is that it still does not execute any command: !modes (css_modes) or !maps (css_maps)

**Comment by Carloscb22** [comment]
```
All Chat][Psicosis (75668661)]: !modes
L 04/01/2024 - 13:15:24: "Psicosis<0><[U:1:75668661]><TERRORIST>" say "!modes"
13:15:24 [INFO] (plugin:GameModeManager) OnModesCommand execution started.
['Psicosis' tick 7768 depth=2 (1816..1817) ping=23ms] CQ bloat: removed 11, max: 10, 10 ticks this frame
SteamNetworkingSockets lock held for 5.1ms.  (Performance warning.)  ServiceThread,CSteamNetworkConnectionBase::Think,SNP_SendPacket,SendUDPacket
This is usually a symptom of a general performance problem such as thread starvation.
```

**Comment by Carloscb22** [comment]
```
13:16:58 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: No current scenario
   at ExecutesPlugin.Managers.GameManager.GetCurrentScenario() in /home/runner/work/cs2-executes/cs2-executes/Managers/GameManager.cs:line 163
   at ExecutesPlugin.ExecutesPlugin.OnRoundFreezeEnd(EventRoundFreezeEnd event, GameEventInfo info) in /home/runner/work/cs2-executes/cs2-executes/ExecutesPlugin.cs:line 436
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
['Psicosis' tick 13660 depth=2 (7743..7744) ping=23ms loss in/out = 8.15%/8.15%] CQ bloat: removed 10, max: 10, 10 ticks this frame
```

**Comment by Carloscb22** [comment]
```
13:23:12 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: No current scenario
   at ExecutesPlugin.Managers.GameManager.GetCurrentScenario() in /home/runner/work/cs2-executes/cs2-executes/Managers/GameManager.cs:line 163
   at ExecutesPlugin.ExecutesPlugin.OnRoundFreezeEnd(EventRoundFreezeEnd event, GameEventInfo info) in /home/runner/work/cs2-executes/cs2-executes/ExecutesPlugin.cs:line 436
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
```

**Comment by nickj609** [comment]
Hey @Carloscb22, would you be able to provide a copy of just the GameModeManager logs from `/game/csgo/addons/counterstrikesharp/logs`? 

There is another new version if you want to give it a try. However, I would also be curious to know if you have the following versions or above:

Metamod:Source v1282+
Counter Strike Sharp v.197+

I can see that the commands are executing successfully from the logs you provided, so if you aren't at the very least seeing a menu it may be a compatibility issue. If the menus are just empty, it's an issue parsing the gamemodes_server.txt file, which the logs from the initial plugin load will help explain.

**Comment by nickj609** [comment]
Hey @Carloscb22, are you still having issues?
