### ISSUE TITLE
Crash in v1.0.45 when switching to GunGame

### ISSUE THREAD

**Issue by kus** [nickj609/GameModeManager#18]
Hi @nickj609 

I updated to **v1.0.45** you can see the [commit](https://github.com/kus/cs2-modded-server/commit/2bdc4eb39f3f7dec514dd98570754b5350efae1f) of what I changed (when rolling back).

Metamod, CounterStrikeSharp is up to date.

I started the server, then via server console switced to GunGame by running `exec gg` and the server crashed.

This looks like it could be the culprit `[INFO] (plugin:GameModeManager) Game has ended. Picking random map from current mode...`. I just switched to GunGame so it shouldn't be switching the map.

```
] exec gg
03:06:28 [INFO] (plugin:GameModeManager) Current mode: Casual
03:06:28 [INFO] (plugin:GameModeManager) New mode: Gun Game
03:06:28 [INFO] (plugin:GameModeManager) Regenerating per map votes...
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote cs_italy removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote cs_italy removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote cs_office removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote cs_office removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_vertigo removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_vertigo removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_ancient removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_ancient removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_anubis removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_anubis removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_dust2 removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_dust2 removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_inferno removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_inferno removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_mirage removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_mirage removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_nuke removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_nuke removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_overpass removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_overpass removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_assembly removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_assembly removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_cbble removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_cbble removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_cache removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_cache removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_pipeline removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_pipeline removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_biome removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_biome removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote mp_raid removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote mp_raid removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_mutiny removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_mutiny removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote cs_assault removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote cs_assault removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_ruins_d_prefab removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_ruins_d_prefab removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote cs_militia removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote cs_militia removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_aztec removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_aztec removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_akiba removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_akiba removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote cs_insertion2 removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote cs_insertion2 removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_train removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_train removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_mills removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_mills removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_thera removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_thera removed
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_season removed
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_season removed
03:06:28 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
03:06:28 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
03:06:28 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
03:06:28 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote ar_shoots added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote ar_shoots added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote ar_baggage added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote ar_baggage added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote ar_pool_day added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote ar_pool_day added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_assembly added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_assembly added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote fy_iceworld added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote fy_iceworld added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote daymare added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote daymare added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote mcdonalds added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote mcdonalds added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote aim_theorem added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote aim_theorem added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_safehouse added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_safehouse added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_lake added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_lake added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote de_bank added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote de_bank added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote fun_bounce added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote fun_bounce added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote 1v1aim_map_longdustversion_d added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote 1v1aim_map_longdustversion_d added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote ar_churches_s2r added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote ar_churches_s2r added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote aim_ag_texture_city_advanced added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote aim_ag_texture_city_advanced added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote traningoutside added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote traningoutside added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote shipment_version_1_0 added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote shipment_version_1_0 added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote aim_ag_texture2 added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote aim_ag_texture2 added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote aim_ag_texture_jungle added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote aim_ag_texture_jungle added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote cs2_bloodstrike added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote cs2_bloodstrike added
03:06:28 [INFO] (plugin:Custom Votes) [CustomVotes] Vote gg_simpsons_vs_flanders_v2 added
info: CS2_CustomVotes.Services.VoteManager[0]
      [CustomVotes] Vote gg_simpsons_vs_flanders_v2 added
03:06:28 [INFO] (cssharp:PluginContext) Unloading plugin CS2Rcon
03:06:28 [INFO] (cssharp:PluginContext) Finished unloading plugin CS2Rcon
03:06:28 [INFO] (cssharp:PluginContext) Loading plugin CS2Rcon
[CS2Rcon] Plugin: CS2Rcon - Version: 1.2.0 by LordFetznschaedl
[CS2Rcon] Allows for server commands to be executed from the client using !rcon
03:06:28 [INFO] (cssharp:PluginContext) Finished loading plugin CS2Rcon
03:06:28 [INFO] (cssharp:PluginContext) Loading plugin GG2
03:06:28 [INFO] (plugin:CS2_GunGame) API registered
03:06:28 [INFO] (plugin:CS2_GunGame) Loading config: csgo/cfg/gungame/gungame.json
Plugin Respawn T and CT on
03:06:29 [INFO] (plugin:CS2_GunGame) [GUNGAME] GG Start, version v1.1.2
03:06:29 [INFO] (cssharp:PluginContext) Finished loading plugin CS2_GunGame
03:06:29 [INFO] (cssharp:PluginContext) Loading plugin CS2-Remove-Map-Weapons
03:06:29.022 [Remove Map Weapons] Plugin: Remove Map Weapons - Version: 1.0.1 by Kus (https://github.com/kus)
03:06:29.022 [Remove Map Weapons] Remove the weapons from the map
03:06:29 [INFO] (cssharp:PluginContext) Finished loading plugin Remove Map Weapons
[GUNGAME]********* Round 1 Start
03:06:29 [INFO] (plugin:CS2_GunGame) [GUNGAME]********* Round 1 Start
[GunGame]********** Start WarmupRound
03:06:29.033 [Remove Map Weapons] OnRoundStart
03:06:29.034 [Remove Map Weapons] Removing map weapons
[CS2_ExecAfter] exec_after_round_start = exec settings/alltalk_on.cfg
[CS2_ExecAfter] exec_after_map_start = exec gg_settings.cfg
03:06:29 [INFO] (plugin:CS2_GunGame) [GunGame_Stats] ***** InitializeDatabaseConnection: SQLite - success
[CS2_ExecAfter] Executing (round start): exec settings/alltalk_on.cfg
[CS2_ExecAfter] exec_after_round_start = exec settings/alltalk_on.cfg
[S_API FAIL] Tried to access Steam interface SteamUtils010 before SteamAPI_Init succeeded.
03:06:29 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
03:06:29 [WARN] (cssharp:Core) Display should not be longer than 26 characters for a CenterHtmlMenu item
03:06:29 [INFO] (plugin:CS2_GunGame) [GunGame] map ar_pool_day loaded
03:06:29 [INFO] (plugin:CS2_GunGame) Loading config: csgo/cfg/gungame/gungame.json
Plugin Respawn T and CT on
03:06:29 [INFO] (plugin:CS2_GunGame) [GUNGAME] GG Start, version v1.1.2
[GunGame]********** Start WarmupRound
03:06:29.206 [Remove Map Weapons] OnMapStartHandler
03:06:29.206 [Remove Map Weapons] Removing map weapons
[03:06:29.221] CSSharp: CGameSystem::BuildGameSessionManifest
execing gg
execing unload_plugins.cfg
execing custom_gg.cfg
execing gg_settings.cfg
execing gamemode_casual.cfg
SV: Convar 'sv_infinite_ammo' is cheat protected, change ignored.
Unknown command 'mp_weapons_glow_on_ground'!
Unknown command 'sv_gameinstructor_enable'!
execing settings/one_round.cfg
Unknown command 'mp_roundtime_deployment'!
Using spawn points configuration 0x3BD9698F
"settings/one_round.cfg executed"
execing settings/alltalk_on.cfg
"settings/alltalk_on.cfg executed"
execing settings/map_voting.cfg
"settings/map_voting.cfg executed"
execing settings/no_drop_weapons.cfg
"settings/no_drop_weapons.cfg executed"
execing bots.cfg
execing custom_bots.cfg
execing custom_gg.cfg
"gg_settings.cfg executed"
"gg.cfg executed"
[All Chat][Console (0)]: "Changing map..."
Changelevel to ar_pool_day
changelevel "ar_pool_day"
CHostStateMgr::QueueNewRequest( Changelevel (ar_pool_day), 3 )
Could not reload plugin "/home/steam/cs2/game/csgo/addons/counterstrikesharp/plugins/RockTheVote/RockTheVote.dll"
Unknown command 'heartbeat'!
Unknown command 'heartbeat'!
execing gungame/gungame.warmupstart.cfg
Unknown command 'heartbeat'!
Unknown command 'heartbeat'!
SV:  CNetworkServerService::StartChangeLevel( (no landmark) )
HostStateRequest::Start(HSR_GAME):  loop(levelload) id(3) addons() desc(Changelevel (ar_pool_day))
SwitchToLoop levelload requested:  id [3] addons []
13.421875 Long frame (RestartRound): 281.08ms elapsed, 3.20ms sim time, 1 ticks, 859..859.
execing settings/alltalk_on.cfg
"settings/alltalk_on.cfg executed"
SV:  IGameSystem::LoopDeactivateAllSystems {
HO:  IGameSystem::LoopDeactivateAllSystems {
HO:  } IGameSystem::LoopDeactivateAllSystems done
SV:  } IGameSystem::LoopDeactivateAllSystems done
SV:  Server shutting down: NETWORK_DISCONNECT_LOOPDEACTIVATE (55)
CNetworkGameServerBase::SetServerState (ss_active -> ss_dead)
SV: CNetworkStringTableContainer::RemoveAllTables:  removing 12 tables
CL: CNetworkStringTableContainer::RemoveAllTables:  removing 12 tables
SV:  CGameRulesGameSystem::GameShutdown uninstalled game rules
SV:  CGameRules::CGameRules destructed
SV:  Level loading started for 'ar_pool_day'
CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
SwitchToLoop game requested:  id [3] addons []
CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
SV:  maxplayers set to 32
Network socket 'server' opened on port 27015
Initializing CSGO VScript Game System
SV:  Executing server defaults
SV:  Executing dedicated server config file
GameTypes: could not find matching game mode value of "" in any game type.
SV:  CGameRulesGameSystem::GameInit installed game rules
execing gungame/gungame.warmupstart.cfg
exec: couldn't exec '{*}cfg/skill1.cfg', unable to read file
execing server_default.cfg
execing server.cfg
execing gamemode_casual.cfg
exec: couldn't exec '{*}cfg/gamemode_casual_server.cfg', unable to read file
exec: couldn't exec '{*}cfg/gamemode_casual_last.cfg', unable to read file
execing env.cfg
"env.cfg executed"
execing settings/bhop_off.cfg
execing settings/movement_restore.cfg
"settings/movement_restore.cfg executed"
"settings/bhop_off.cfg executed"
Unknown command 'sv_holiday_mode'!
execing bots.cfg
execing custom_bots.cfg
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.
execing settings/map_voting.cfg
"settings/map_voting.cfg executed"
execing custom_all.cfg
"server.cfg executed"
03:06:31 [INFO] (plugin:GameModeManager) Game has ended. Picking random map from current mode...
[03:06:31.005] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.005] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.005] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.005] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.006] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.007] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.007] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.007] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.007] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.007] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.007] CSSharp: Native d8f03fd4 was invoked on a non-main thread
[03:06:31.007] CSSharp: Native 376a0359 was invoked on a non-main thread
Unhandled exception. CounterStrikeSharp.API.Core.NativeException: Invoked on a non-main thread
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 176
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternalVoid(Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 77
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`6.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 156
   at CounterStrikeSharp.API.Server.PrintToChatAll(String message) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Server.cs:line 135
   at GameModeManager.RotationManager.TriggerRotation() in C:\Users\nickj\OneDrive\Documents\CS2\plugins\GameModeManager\Core\RotationManager.cs:line 139
   at GameModeManager.TimeLimitManager.<StartTimer>b__16_0(Object <p0>) in C:\Users\nickj\OneDrive\Documents\CS2\plugins\GameModeManager\Core\TimeLimitManager.cs:line 81
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by mavproductions** [comment]
Can confirm getting similar errors.

**Comment by nickj609** [comment]
Hey guys! Thanks for letting me know. Pretty sure its an issue with the rotation settings as you have identified. Will be looking into this soon :)

**Comment by nickj609** [comment]
Apologies for the delay on this guys. Wanted to follow up here that I have a new version prepped that will be released in the next couple of days. It will contain some exciting new features but will also address these issues presented in my last build.

**Comment by nickj609** [comment]
This issue should be resolved in the latest release. Please reopen if you still experience issues.

https://github.com/nickj609/GameModeManager/releases/tag/v1.0.46
