### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Geant200** [nickj609/GameModeManager#19]
When I launch the server and join it.

CSS : build-246-windows-a87bd25
GameModeManager : 1.0.45
Sys : Windows Server 2022
```
2024-06-29 13:06:05.198 +02:00 [EROR] plugin:GameModeManager Invalid: TimeLeft command cannot be enabled with RTV.
2024-06-29 13:06:05.205 +02:00 [EROR] (cssharp:PluginManager) Failed to load plugin from E:\AMPDatastore\Instances\War-TeamFr-ServeurPrincipal01\counter-strike2\730\game\csgo\addons\counterstrikesharp\plugins\GameModeManager\GameModeManager.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Invalid: TimeLeft command cannot be enabled with RTV.
   at GameModeManager.Plugin.OnConfigParsed(Config _config) in C:\Users\nickj\OneDrive\Documents\CS2\plugins\GameModeManager\Config.cs:line 284
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 392
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 217
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
```

```
2024-06-29 13:06:05.277 +02:00 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at GameModeManager.Plugin.OnAllPluginsLoaded(Boolean hotReload) in C:\Users\nickj\OneDrive\Documents\CS2\plugins\GameModeManager\Plugin.cs:line 99
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 106
```

```
2024-06-29 13:01:57.671 +02:00 [EROR] plugin:GameModeManager Invalid: TimeLeft command cannot be enabled with RTV.
2024-06-29 13:04:55.270 +02:00 [EROR] plugin:GameModeManager Invalid: TimeLeft command cannot be enabled with RTV.
2024-06-29 13:06:05.198 +02:00 [EROR] plugin:GameModeManager Invalid: TimeLeft command cannot be enabled with RTV.
2024-06-29 13:08:17.536 +02:00 [EROR] plugin:GameModeManager Invalid: TimeLeft command cannot be enabled with RTV.
```

**Comment by Geant200** [comment]
Hello. Still on vacation ^^?.

**Comment by Geant200** [comment]
Hello.

Can you give me news of the project when a modification will be made to make it compatible with the latest version of CounterStrikeSharp.

Thank you in advance.

**Comment by nickj609** [comment]
Hey @Geant200 , apologies on the delay in my response. I am working on an updated version as we speak! I should have a release in the next couple of days. 

Regarding the original issue in this thread, it looks like the TimeLeft command is enabled while RTV is enabled. This error suggests that you need to disable one or the other in the .json config file.

Error: "TimeLeft command cannot be enabled with RTV."

I hope this helps you get up and running in the meantime. Also, FYI do not use the latest build, as it is currently broken. Use 1 build behind the latest release for the stable build. 

Here is a quick look at what the next version has to offer:

- Improved mode schedules
- Plugin compatibility updates.
- Shared API for cross-plugin development
- Improved voting menus for per map, mode, and setting votes. 
- The ability to force time limits (mp_timelimit), even when no players are connected.
- New Warmup Modes that can be set for all maps in a mode or on a per-map basis (Map Exec)

**Comment by Geant200** [comment]
Thank you for your reply ^^.

Thanks for the information ^^ I will wait for the next version of your plugin, thank you very much for the rest ^^.

**Comment by nickj609** [comment]
@Geant200 , great timing! Just posted the latest version/release. Apologies on the delay, there were alot of structural changes.

This issue should now be resolved in the latest release. Please reopen if you still experience issues.

https://github.com/nickj609/GameModeManager/releases/tag/v1.0.46

**Comment by Geant200** [comment]
Thanks I will test that ^^.
